#!/bin/bash
if [ -z $1 -o ! -e $1 ]; then
  echo "Usage: runit <file>"
  exit 1
fi 
datei=$1
erweiterung=${datei##*.}
program=${datei%.*}
zeile1=`head -n 1 $datei`
shebang=${zeile1:0:2}

run=`head -n 10 $datei | sed -n -e 's/^.*Run: \(.*\)$/\1/p'`

if [ "$shebang" == "#!" ] 
then
  echo "> Making executable..."
  chmod +x $datei
  if [ -n "$run" ]
  then
    echo "> Found Run: $run"
    $run
  else 
    echo "> Starting: ./$datei"
    ./$datei
  fi
  exit 0
fi

compile=`head -n 10 $datei | sed -n -e 's/^.*Compile: \(.*\)$/\1/p'`

if [ -n "$compile" ]
then
  echo "> Found Compile: $compile"
  $compile
else 
  case "$erweiterung" in
    adb)
      compile="gnatmake -gnaty3acefhiklmnrpt $datei"
      ;;
    cpp)
      compile="g++ $datei -o $program"
      ;;
    c)
      compile="gcc -std=gnu99 $datei -o $program"
      ;;
    java)
      compile="javac $datei"
      [ -z "$run" ] && run="java $program"
      ;;
    txt)
      compile="apt2pdf"
      [ -z "$run" ] && run="echo 'out.pdf should be in the directory.'"
      ;;
    apt)
      compile="apt2pdf $datei"
      [ -z "$run" ] && run="echo 'out.pdf should be in the directory.'"
      ;;
  esac
  if [ -n "$compile" ]
  then
    echo "> Guessing Compile: $compile"
    $compile
    if [ $? != 0 ]; then
      exit 1;
    fi
  fi
fi

if [ -n "$run" ]
then
  echo "> Found Run: $run"
  time $run
else
  echo "> Guessing Run: ./$program"
  time ./$program
fi
